name: rnaseq
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::r-base>=4.2.0
  - conda-forge::r-ggplot2>=3.1.0
  - bioconda::star=2.7.6a
  - bioconda::rsem=1.3.1
  - bioconda::trim-galore>=0.6.7
  - bioconda::bioconductor-deseq2>=1.38.0
  - bioconda::bioconductor-enhancedvolcano>=1.18.0
  - bioconda::bioconductor-fgsea>=1.26.0
  
